// Generated by CoffeeScript 1.6.3
(function() {
  var gpio, ledOn;

  gpio = require("pi-gpio");

  ledOn = true;

  setInterval(function() {
    gpio.write(11, ledOn ? 0 : 1);
    return ledOn = ledOn ? false : true;
  }, 2000);

}).call(this);
