// Generated by CoffeeScript 1.7.1
(function() {
  var RaspiCam, camera, options;

  RaspiCam = require('raspicam');

  options = {
    mode: 'photo',
    output: 'stills/pic_%d.png',
    w: 1280,
    h: 720,
    e: 'png',
    t: '2000',
    tl: false
  };

  camera = new RaspiCam(options);

  camera.start();

  camera.on('started', function() {
    return console.log('started');
  });

  camera.on('read', function(err, filename) {
    return console.log('saved');
  });

  camera.on('exited', function() {
    return console.log('exited');
  });

}).call(this);
