// Generated by CoffeeScript 1.7.1
var RaspiCam, camera, options;

RaspiCam = require('raspicam');

options = {
  mode: 'photo',
  output: '/tmp/pictures/pic_%d.png',
  encoding: 'png',
  timeout: '2000',
  timelapse: false
};

camera = new RaspiCam(options);

camera.start();

camera.on('started', function() {
  return console.log('started');
});

camera.on('read', function(err, filename) {
  return console.log('saved');
});

camera.on('exited', function() {
  return console.log('exited');
});
