// Generated by CoffeeScript 1.7.1
(function() {
  var gpio, led;

  gpio = require('pi-gpio');

  led = {
    red: 11,
    green: 13,
    blue: 15
  };

  gpio.open(led.red, "output", function() {
    return gpio.write(led.red, 1);
  });

}).call(this);
